//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RENTACARAPP.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAKSIYON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAKSIYON()
        {
            this.TCEZA = new HashSet<TCEZA>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ARABA { get; set; }
        public Nullable<int> UYE { get; set; }
        public Nullable<int> SATISELEMANI { get; set; }
        public Nullable<System.DateTime> KIRALAMATARIH { get; set; }
        public Nullable<System.DateTime> TESLIMTARIH { get; set; }
        public Nullable<System.DateTime> GUNOLCER { get; set; }
    
        public virtual TARABA TARABA { get; set; }
        public virtual TUYELER TUYELER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TCEZA> TCEZA { get; set; }
        public virtual TSATISELEMAN TSATISELEMAN { get; set; }
    }
}
