//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RENTACARAPP.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCEZA
    {
        public int ID { get; set; }
        public Nullable<int> UYE { get; set; }
        public Nullable<System.DateTime> BASLANGICT { get; set; }
        public Nullable<System.DateTime> BITIST { get; set; }
        public Nullable<decimal> PARA { get; set; }
        public Nullable<int> AKSIYON { get; set; }
    
        public virtual TAKSIYON TAKSIYON { get; set; }
        public virtual TUYELER TUYELER { get; set; }
    }
}
