//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RENTACARAPP.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUYELER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TUYELER()
        {
            this.TAKSIYON = new HashSet<TAKSIYON>();
            this.TCEZA = new HashSet<TCEZA>();
        }
    
        public int ID { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string EPOSTA { get; set; }
        public string NICKNAME { get; set; }
        public string SIFRE { get; set; }
        public string UYEFOTO { get; set; }
        public string TELNO { get; set; }
        public Nullable<bool> EHLIYET { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAKSIYON> TAKSIYON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TCEZA> TCEZA { get; set; }
    }
}
